### ISSUE TITLE
Basicworm skeleton as ndarray support in NormalizedWorm

### ISSUE THREAD

**Issue by JimHokanson** [openworm/open-worm-analysis-toolbox#124]
If we allow the skeleton to be a 3d numpy array (fixed # of points per frame), rather than a list with data for individual frames as each element, then we need to build support into NormalizedWorm for handling this.

**Comment by JimHokanson** [comment]
My preference would be to transform this input in BasicWorm so that it matches our current form (a list of ndarrays)

**Comment by MichaelCurrie** [comment]
Right now BasicWorm represents skeletons and contours as lists of 2d numpy arrays, so there is no need for 3d ndarray support in NormalizedWorm.

That said, once BasicWorm inherits from WCONWorms, the skeleton and contour will be represented as a pandas dataframe, with an "aspect_size" entry for each timeframe specifying how many articulation points there are, and NaNs are used to pad non-maximal skeletons.  That's by far the more processing-efficient approach, I bet, because it leverages the strided array representation of numpy ndarrays.  We have to allocate a bit more memory because of the NaNs, but assuming the maximum aspect size is not more than 100% of the average aspect size across timeframes this should not be significant.
