### ISSUE TITLE
Possible bad data point in eigenworms file

### ISSUE THREAD

**Issue by MichaelCurrie** [openworm/open-worm-analysis-toolbox#143]
I eyeballed the following bad data point (the last one point seems wrong) on the black eigenworm in the [following plot](https://github.com/openworm/movement_validation/blob/master/examples/plot_eigenworms.py):

![image](https://cloud.githubusercontent.com/assets/5267078/8270615/1c891e34-17a5-11e5-8c67-b602d08600a0.png)

@balazs1987 do you agree?  I'm guessing since eigenworms are calculated from principal component analysis they should be infinitely differentiable.

**Comment by MichaelCurrie** [comment]
@balazs1987 or @aexbrown do you agree?  I'd appreciate your comments on this one.

**Comment by Ichoran** [comment]
I don't understand what all the lines mean, but if the X-axis is time and the Y-axis is component value, and the trace stops because the animal was lost or did something weird (like execute an omega turn), you can certainly have a discontinuity.  You'd expect one, for example, when going from a C shape to an O shape, or colliding with an egg or a dark edge of bacteria or any number of other things.  That only one component changes drastically surprises me, though, and makes me wonder whether it's a bug in the analysis.

**Comment by MichaelCurrie** [comment]
Sorry I didn't label it: X-axis is segment number and Y-axis is "normalized angle"; viz. [Brown *et al.* 2012](http://www.pnas.org/content/110/2/791.full.pdf)

**Comment by MichaelCurrie** [comment]
No one has replied so I'm going to close this issue since it hasn't caused any problems.  We can re-open if we want to fix this later.
